version: '3.3'

services:
  tmdb-project-kairos:
    image: tmdb-project-kairos
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "${DOCKER_HOST_PORT}:80"
    environment:
      - API_KEY=${API_KEY}
    restart: always
